version: '3.8'

services:
  backend:
    build:
      context: ./tfg_backend
      dockerfile: Dockerfile
      args:
        ARG_API_PORT: ${API_PORT}
        ARG_IP_FRONT: ${IP_FRONT}
        ARG_DB_HOST: ${DB_HOST}
        ARG_DB_PORT: ${DB_PORT}
        ARG_DB_USER: ${DB_USER}
        ARG_DB_PASSWORD: ${DB_PASSWORD}
        ARG_DB_NAME: ${DB_NAME}
        ARG_MONGO_AUTH_DB: ${MONGO_AUTH_DB}
        ARG_JWT_SECRET: ${JWT_SECRET}
        ARG_JWT_AUDIENCE: ${JWT_AUDIENCE}
        ARG_JWT_ISSUER: ${JWT_ISSUER}
        ARG_JWT_EXPIRATION: ${JWT_EXPIRATION}
        ARG_APP_NAME: ${APP_NAME}
        ARG_APP_VERSION: ${APP_VERSION}
    environment:
      - API_PORT=${API_PORT}
      - IP_FRONT=${IP_FRONT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - MONGO_AUTH_DB=${MONGO_AUTH_DB}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - APP_NAME=${APP_NAME}
      - APP_VERSION=${APP_VERSION}
    ports:
      - "5000:5000"
    volumes:
      - ./tfg_backend/plantillas:/app/plantillas
      - ./tfg_backend/data:/app/data
    depends_on:
      - mongo
    restart: always

  frontend:
    build:
      context: ./tfg_frontend
      dockerfile: Dockerfile
      args:
        IP_FRONT: ${IP_FRONT}
        API_HOST: ${API_HOST}
        API_PORT: ${API_PORT}
    environment:
      - IP_FRONT=${IP_FRONT}
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: always

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - MONGO_AUTH_DB=${MONGO_AUTH_DB}
      - DB_PORT=${DB_PORT}
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    restart: always

volumes:
  mongo-data:
